name: safe
description: Safe Passenger Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.25+36

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  firebase_auth_web: ^5.2.8
  firebase_messaging: ^14.2.5
  #firebase_analytics: ^9.1.2
  firebase_storage: ^11.0.14
  firebase_remote_config: ^3.0.13
  cloud_firestore: ^4.4.3
  firebase_database: ^10.0.5
  fluttertoast: ^8.0.8
  google_maps_flutter: ^2.1.1
  geolocator: ^9.0.2
  http: ^0.13.4
  provider: ^6.0.2
  flutter_polyline_points: ^1.0.0
  google_polyline_algorithm: ^3.1.0
  font_awesome_flutter: ^9.2.0
  animated_text_kit: ^4.2.1
  vector_math: ^2.1.1
  json_annotation: ^4.0.0
  shared_preferences: ^2.0.10
  synchronized: ^3.0.0
  flutter_local_notifications: ^9.3.3
  future_progress_dialog: ^0.2.0
  rounded_loading_button: ^2.0.9
  package_info_plus: ^3.0.3
  intl: ^0.17.0
  flutter_native_timezone: ^2.0.0
  url_launcher: ^6.0.20
  email_validator: ^2.0.1
  connectivity_plus: ^2.2.1
  flutter_rating_bar: ^4.0.0
  country_code_picker: ^2.0.2
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.5+3
  file: ^6.1.4
  uuid: ^3.0.6
  widget_mask: ^1.0.0+0
  #bubble_bottom_bar: ^2.0.0
  badges: ^2.0.0-nullsafety.1
  syncfusion_flutter_charts: ^20.3.59
  share_plus: ^4.0.10+1
  launch_review:
    path: ./launch_review
  flutter_sensors: ^1.0.1
  location: ^4.4.0
  flutter_geofire:
    path: ./flutter_geofire
  dartx: ^1.1.0
  audioplayers: ^3.0.1
  back_button_interceptor:
    path: ./back_button_interceptor
  sms_autofill:
    path: ./sms_autofill
  disable_battery_optimization:
    path: ./disable_battery_optimization
  #vibration: ^1.7.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  dio: ^5.0.1
  json_serializable: ^6.6.2
  test: ^1.19.5

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

flutter:
  uses-material-design: true
  generate: true

  assets:
    - images/car.png
    - images/dot_blue.png
    - images/dot_red.png
    - images/redmarker.png
    - images/pin_location.png
    - images/car_side.png
    - images/minibus.png
    - images/minivan.png
    - images/pin_logo.png
    - images/economy.png
    - images/minivan_safe.png
    - images/minbus_safe.png
    - images/white_logo.png
    - images/logoBack.png
    - images/safeLogo.png
    - images/mask1.png
    - images/mask2.png
    - images/input.png
    - images/whiteSafeLogo.png
    - images/referal.png
    - images/location.png
    - images/safe_gray.png
    - images/white_logo_1.png
    - images/pin_map_locator.png
    - images/telelogo.png
    - images/logo.png
    - images/lada.png
    - images/lady.png
    - images/motor.png
    - images/shared.png
    - images/share2.png
    - images/share3.png
    - images/new_arrow.png
    - images/arrow.png
    - images/yegna.png
    - images/compass_base.png
    - images/avanza_car.png
    - images/s_avanza.png
    - images/s_suzuki.png
    - images/back_pic.png
    - images/swip_logo.png
    - assets/

  fonts:
    - family: Signatra
      fonts:
        - asset: fonts/Signatra.ttf

    - family: Lato
      fonts:
        - asset: fonts/Lato-Bold.ttf

    - family: Brand-Regular
      fonts:
        - asset: fonts/bolt-regular.ttf
    - family: Brand Bold
      fonts:
        - asset: fonts/bolt-semibold.ttf
    - family: Adwa Regular
      fonts:
        - asset: fonts/አድዋ.ttf
    - family: Nokia Pure Headline Bold
      fonts:
        - asset: fonts/ኖኪያ Bold.ttf



