name: safe
description: Safe Passenger Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.11+11

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9
  firebase_auth_web: ^3.3.9
  firebase_messaging: ^11.2.8
  firebase_analytics: ^9.1.2
  firebase_storage: ^10.2.9
  cloud_firestore: ^3.1.10
  firebase_database: ^9.0.8
  fluttertoast: ^8.0.8
  google_maps_flutter: ^2.1.1
  geolocator: ^7.1.0
  http: ^0.13.4
  provider: ^6.0.2
  flutter_polyline_points: ^1.0.0
  font_awesome_flutter: ^9.2.0
  animated_text_kit: ^4.2.1
  flutter_geofire: ^2.0.1
  vector_math: ^2.1.1
  json_annotation: ^4.0.0
  shared_preferences: ^2.0.12
  synchronized: ^3.0.0
  firebase_remote_config: ^2.0.0
  flutter_local_notifications: ^9.3.3
  future_progress_dialog: ^0.2.0
  rounded_loading_button: ^2.0.9
  package_info: ^2.0.2
  intl: ^0.17.0
  flutter_native_timezone: ^2.0.0
  url_launcher: ^6.0.20
  email_validator: ^2.0.1
  connectivity_plus: ^2.2.1
  flutter_rating_bar: ^4.0.0
  firebase: ^9.0.3
  country_code_picker: ^2.0.2
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.5+3
  uuid: ^3.0.6
  widget_mask: ^1.0.0+0
  bubble_bottom_bar: ^2.0.0
  syncfusion_flutter_charts: ^20.3.59

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  dio: ^4.0.4
  json_serializable: ^6.1.4
  test: ^1.19.5

dependency_overrides:
  shared_preferences_android: 2.0.10

flutter:
  uses-material-design: true
  generate: true

  assets:
    - images/car.png
    - images/dot_blue.png
    - images/dot_red.png
    - images/redmarker.png
    - images/user_icon.png
    - images/pin_location.png
    - images/separator.png
    - images/logo.png
    - images/wait.png
    - images/car_side.png
    - images/yellow_car.png
    - images/minibus.png
    - images/minivan.png
    - images/pin_logo.png
    - images/economy.png
    - images/minivan_safe.png
    - images/minbus_safe.png
    - images/white_logo.png
    - images/logoBack.png
    - images/safeLogo.png
    - images/mask1.png
    - images/mask2.png
    - images/input.png
    - images/whiteSafeLogo.png
    - images/referal.png
    - images/location.png
    - images/safe_gray.png


  fonts:
    - family: Signatra
      fonts:
        - asset: fonts/Signatra.ttf

    - family: Lato
      fonts:
        - asset: fonts/Lato-Bold.ttf

    - family: Brand-Regular
      fonts:
        - asset: fonts/bolt-regular.ttf
    - family: Brand Bold
      fonts:
        - asset: fonts/bolt-semibold.ttf



