name: launch_review
description: A Flutter plugin to assist in leaving user reviews/ratings in Google Play Store and Apple App Store.
version: 3.0.1

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.iyaffle.launchreview
        pluginClass: LaunchReviewPlugin

environment:  
  sdk: ">=2.12.0 <3.0.0"
  #flutter: ">=1.20.0"
